{{- if and .Values.pgadmin.enabled .Values.pgadmin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "postgresql-pgadmin.pgadmin.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql-pgadmin.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
  {{- with .Values.pgadmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pgadmin.ingress.className }}
  ingressClassName: {{ .Values.pgadmin.ingress.className }}
  {{- end }}
  {{- if .Values.pgadmin.ingress.tls }}
  tls:
    {{- toYaml .Values.pgadmin.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.pgadmin.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "postgresql-pgadmin.pgadmin.serviceName" $ }}
                port:
                  number: {{ $.Values.pgadmin.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
