{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-pgadmin.postgresql.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql-pgadmin.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "postgresql-pgadmin.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-pgadmin.pgadmin.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "postgresql-pgadmin.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
    - name: http
      port: {{ .Values.pgadmin.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "postgresql-pgadmin.selectorLabels" . | nindent 4 }}
{{- end }}
